name: OSS Contribution Histogram

on:
  schedule:
    - cron: '0 0 * * *'  # Run on at midnight UTC
  workflow_dispatch:
    inputs:
      targets:
        description: 'Target repositories and usernames (format: username,owner/repo [username,owner/repo ...])'
        required: true
        type: string
        default: 'peterxcli,apache/ozone'

env:
  TARGETS: ${{ inputs.targets }} || 'peterxcli,apache/ozone'

jobs:
  update-histogram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run script to generate histogram
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python gh-contribution-graph-generator.py ${{ env.TARGETS }}

      - name: Commit and push updated image
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add *.png
          git commit -m "Update PR histogram" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
