name: OSS Contribution Histogram

on:
  schedule:
    - cron: '0 0 * * *'  # Run on at midnight UTC
  workflow_dispatch:
    inputs:
      targets:
        description: 'Target repositories and usernames (format: username,owner/repo [username,owner/repo ...])'
        required: true
        type: string
        default: 'peterxcli,apache/ozone'

env:
  TARGETS: ${{ inputs.targets }} || 'peterxcli,apache/ozone'

jobs:
  update-histogram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Contribution Histogram
        uses: peterxcli/gh-contribution-histogram-action@v1.0
        with:
          targets: ${{ env.TARGETS }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: 'histograms'

      - name: Commit and push updated image
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add histograms/*.png
          git commit -m "Update PR histogram" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
